rest:
  ssl: true
  host: sandbox.dspace.org
  port: 443
  nameSpace: /server

themes:
  - name: gallatin-syllabi
    extends: fda
    handle: 2451/34841
      
      
  - name: fda
    headTags:
      - tagName: link
        attributes: 
          rel: icon
          href: https://cdn.library.nyu.edu/images/favicon.ico # Path to your favicon file
          sizes: any
